name: End-to-end tests with Edge
on: 
  push:
  schedule:
    - cron: '0 8 * * *'
    
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: 
          browser: edge
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: cypress/reports
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore